#!/usr/bin/env python
import os
import sys

if (len(sys.argv) == 1) or (sys.argv[1] == 'help'):
    print """Fetch CLI:
- fetch <help>: displays this help screen
- fetch <start> [apis]: starts fetch using the specified APIs
    - e: evernote
    - g: github
    - p: phone call
    - s: slack
    - t: text message
    - T: twitter
    - y: yo 
- fetch <send> <recipient>: emails the recipient a complete log file"""
elif sys.argv[1] == 'send':
	if len(sys.argv) <= 2:
		print "Incorrect usage! Type 'fetch send [recipient]' to send a log file."
	else:
		os.system('python /home/send.py %s' % sys.argv[2])
elif sys.argv[1] == 'start':
    if len(sys.argv) >= 2:
        if sys.argv[2] == 'all':
            os.system('python /home/error.py')
        else:
    	    os.system('python /home/error.py %s' % sys.argv[2])
    else:
    	os.system('python /home/error.py')
